query Products(
  $category: String
  $collection: String
  $specificationFilters: [String]
  $orderBy: String
  $from: Int
  $to: Int
  $hideUnavailableItems: Boolean = false
) {
  products(
    category: $category
    collection: $collection
    specificationFilters: $specificationFilters
    orderBy: $orderBy
    from: $from
    to: $to
    hideUnavailableItems: $hideUnavailableItems
  ) @context(provider: "vtex.search-graphql") {
    cacheId
    productId
    productName
    productReference
    description
    link
    linkText
    brand
    brandId
    titleTag
    metaTagDescription
    specificationGroups {
      name
      specifications {
        name
        values
      }
    }
    items {
      name
      nameComplete
      itemId
      measurementUnit
      unitMultiplier
      referenceId {
        Key
        Value
      }
      images {
        imageId
        imageLabel
        imageTag
        imageUrl
        imageText
      }
      variations {
        name
        values
      }
      sellers {
        sellerId
        sellerName
        commertialOffer {
          Installments(criteria: MAX) {
            Value
            InterestRate
            TotalValuePlusInterestRate
            NumberOfInstallments
            Name
          }
          AvailableQuantity
          Price
          ListPrice
          PriceWithoutDiscount
          RewardValue
          PriceValidUntil
          teasers {
            name
          }
          discountHighlights {
            name
          }
        }
      }
    }
    productClusters {
      id
      name
    }
    properties {
      name
      values
    }
  }
}
