query ProductRecommendations(
  $identifier: ProductUniqueIdentifier
  $type: CrossSelingInputEnum
) {
  productRecommendations(identifier: $identifier, type: $type) {
    cacheId
    productId
    productName
    description
    categories
    link
    linkText
    brand
    items {
      name
      itemId
      referenceId {
        Value
      }
      images {
        imageId
        imageLabel
        imageTag
        imageUrl
        imageText
      }
      sellers {
        sellerId
        sellerName
        addToCartLink
        sellerDefault
        commertialOffer {
          Price
          ListPrice
          PriceWithoutDiscount
          RewardValue
          PriceValidUntil
          AvailableQuantity
          Tax
          CacheVersionUsedToCallCheckout
          Installments (criteria: MAX) {
            Value
            InterestRate
            TotalValuePlusInterestRate
            NumberOfInstallments
            Name
          }
        }
      }
    }
  }
}
