query RelatedProducts($slug: String) {
  product(slug: $slug) {
    cacheId
    recommendations {
      view {
        cacheId
        productId
        productName
        description
        categories
        link
        linkText
        brand
        items {
          name
          itemId
          referenceId {
            Value
          }
          images {
            imageUrl
            imageTag
          }
          sellers {
            commertialOffer {
              Installments {
                Value
                InterestRate
                TotalValuePlusInterestRate
                NumberOfInstallments
                Name
              }
              Price
              ListPrice
            }
          }
        }
      }
    }
  }
}
